# Change these first
owner: Thexyz # Your GitHub organization or username, where this repository lives
repo: Downly # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com  
  - name: Down eupx.com
    url: https://eupx.com
  - name: Thexyz
    url: https://www.thexyz.com
    icon: https://www.thexyz.com/favicon.ico
    status-website: https://www.thexyz.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: downly.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Downly
  introTitle: "**Downly** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page checks **real-time** data to determine current server status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/thexyz/downly

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

user-agent: thexyz
i18n:
  footer: This project is [open source]($REPO), powered by [Thexyz](https://www.thexyz.com)
