# Change these first
owner: Thexyz # Your GitHub organization or username, where this repository lives
repo: Downly # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com  
  - name: Twitter
    url: https://twitter.com 
  - name: Facebook
    url: https://facebook.com   
  - name: Microsoft
    url: https://www.microsoft.com
  - name: Amazon
    url: https://amazon.com 
  - name: Reddit
    url: https://www.reddit.com
  - name: Apple
    url: https://www.apple.com   
  - name: EUPX
    url: https://eupx.com
    method: POST
  - name: Thexyz
    url: https://www.thexyz.com
    icon: https://www.thexyz.com/favicon.ico
    status-website: https://www.thexyz.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: downly.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Thexyz/downly/fe24ef565ab79cf43ea185a70b8c91ec175f41d6/assets/downly.svg
  name: Downly
  introTitle: "**Downly** is a bot that checks the status of websites with a regular ping and makes the data publicly available."
  introMessage: This status page checks **real-time** services to determine current server status.
  navbar:
    - title: Status
      href: /
    - title: DNS
      href: https://downly.net/start.html

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

user-agent: thexyz
i18n:
  footer: This project is [open source]($REPO), if you need help, check the [Wiki](https://wiki.downly.net)
  
  status-website:
  customHeadHtml: "01795509e97764dd6cf81cf164bacb68ad31f491"
  favicon: https://github.com/Thexyz/downly/blob/master/assets/downly-favicon.png
  faviconSvg: https://raw.githubusercontent.com/Thexyz/downly/4171886168d7a52f776a983c2a540d327100a586/assets/downly.svg

  
  NOTIFICATION_EMAIL:	"true"
  NOTIFICATION_EMAIL_FROM: "bot@downly.net"
  NOTIFICATION_EMAIL_TO: "alert_new@downly.net"
  
  i18n:
  up: "✅ Up"
  degraded: "⚠️ Degraded"
  down: "🚨 Down"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "All monitered services are currenly operational"
  degradedPerformance: "⚠️ Degraded performance"
  completeOutage: "🚨 Complete outage"
  

